[package]
name = "graphql-tools"
version = "0.1.0"
edition = "2021"
authors = ["Martin Disch <martindisch@gmail.com>"]
description = "CLI tools for working with GraphQL"
repository = "https://github.com/martindisch/graphql-tools"
license = "MIT OR Apache-2.0"

[dependencies]
